//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmdAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pdf
    {
        public int PdfId { get; set; }
        public string PdfName { get; set; }
        public string PdfPath { get; set; }
        public Nullable<decimal> PdfSize { get; set; }
        public string PdfDetail { get; set; }
    }
}
